spring:
  application:
    name: data-exchange
  datasource:
    postgres:
      jdbcUrl: jdbc:postgresql://172.16.0.109:5433/rcims?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: rcims
      password: stardcl
      driver-class-name: org.postgresql.Driver
    mysql:
      jdbcUrl: jdbc:mysql://172.16.0.109:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
      username: root
      password: startsi
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      postgres:
        show-sql: true
        properties:
          hibernate:
            hbm2ddl.auto: update
            naming:
              physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      mysql:
        show-sql: true
        properties:
          hibernate:
            hbm2ddl.auto: update
